# Docker Compose 配置 (可选部署方式)
# 使用方法: docker-compose up -d

version: '3.8'

services:
  yt-dlpservice:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: yt-dlpservice
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - /tmp/yt-dlpservice:/tmp/yt-dlpservice
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - redis
    networks:
      - yt-dlp-network

  # Redis (可选，用于任务队列)
  redis:
    image: redis:7-alpine
    container_name: yt-dlpservice-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - yt-dlp-network

volumes:
  redis_data:

networks:
  yt-dlp-network:
    driver: bridge 